### ISSUE TITLE
[BUG] current.setKazagumo is not a function

### ISSUE THREAD

**Issue by realpukhraj** [Takiyo0/Kazagumo#31]
```js
TypeError: current.setKazagumo is not a function
1|real     |     at MorePlayer.<anonymous> (/home/ubuntu/Data/Real/node_modules/kazagumo/dist/Managers/KazagumoPlayer.js:223:21)
1|real     |     at Generator.next (<anonymous>)
1|real     |     at /home/ubuntu/Data/Real/node_modules/kazagumo/dist/Managers/KazagumoPlayer.js:8:71
1|real     |     at new Promise (<anonymous>)
1|real     |     at __awaiter (/home/ubuntu/Data/Real/node_modules/kazagumo/dist/Managers/KazagumoPlayer.js:4:12)
1|real     |     at MorePlayer.play (/home/ubuntu/Data/Real/node_modules/kazagumo/dist/Managers/KazagumoPlayer.js:204:16)
1|real     |     at Player.<anonymous> (/home/ubuntu/Data/Real/node_modules/kazagumo/dist/Managers/KazagumoPlayer.js:90:25)
1|real     |     at Player.emit (node:events:513:28)
1|real     |     at Player.onPlayerEvent (/home/ubuntu/Data/Real/node_modules/shoukaku/dist/src/guild/Player.js:346:22)
1|real     |     at Player.onLavalinkMessage (/home/ubuntu/Data/Real/node_modules/shoukaku/dist/src/guild/Player.js:329:18)
```
 When a track end and player is not destroyed but next song is not playable as it is mentioned 

**Version:**
 - node.js: [e.g. 16.19.0]
 - Kazagumo [e.g. 1.0.2]

**Comment by realpukhraj** [comment]
NVM i resolved
